const data = {
  products: [
    {
      name: "Nikeasdasd",
      slug: "asdasdadsad",
      category: "Shirts",
      image: "/images/remera.jpg",
      price: 120,
      stock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "sdadasdasd",
    },
    {
      name: "Nikesssss",
      slug: "sssssssss",
      category: "Shirts",
      image: "/images/remera.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "sdadasdasd",
    },
    {
      name: "Nike",
      slug: "naaaaaaaaaa",
      category: "Shirts",
      image: "/images/remera.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "sdadasdasd",
    },
    {
      name: "Nikeeeeeeeeee",
      slug: "hghghgghhgh",
      category: "Shirts",
      image: "/images/remera.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "sdadasdasd",
    },
  ],
};

export default data