const data = {
  products: [
    {
      name: "Nike",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/remera.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 4.5,
      reviews: 10,
      description: "sdadasdasd",
    },
    {
      name: "Nike",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/conjunto.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 4.5,
      reviews: 10,
      description: "sdadasdasd",
    },
    {
      name: "Nike",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/pantalon.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 4.5,
      reviews: 10,
      description: "sdadasdasd",
    },
    {
      name: "Nike",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/zapatilla.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 4.5,
      reviews: 10,
      description: "sdadasdasd",
    },
    {
      name: "Nike",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/remera.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: 4.5,
      reviews: 10,
      description: "sdadasdasd",
    },
  ],
};

export default data